theme: jekyll-theme-minimal
title: Satnam Singh
layout: personal
description: Satnam Singh's personal website
logo: images/mad_scientist_small.jpg
url: https://raintown.org
exclude:
  - Makefile
  - push.sh
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock
footer-links:
  github: satnam6502
  twitter: satnam6502
twitter:
  username: satnam6502
  card: summary_large_image
